apiVersion: v1
kind: PersistentVolume
metadata:
  name: pqlite-pv-volume
  labels:
    type: local
    app: pqlite
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/pqlite"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pqlite-pvc-claim
  labels:
    app: pqlite
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
