name: PQLite CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-11, windows-latest]
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare enviroment
        run: |
            python -m pip install --upgrade pip
            python -m pip install wheel
            pip install -r .github/requirements-test.txt

      - name: Build and install
        run: python -m pip install -e .

      - name: Test
        run: |
            pytest --suppress-no-test-exit-code -v -s tests/
